spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: false

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://team-m.cyabzp8jcj3s.ap-northeast-2.rds.amazonaws.com:3306/metamon?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
#    username: sparcs
#    password: QXrhmBhKKDrTHdF7Zzk3U3tx
#  jpa:
#    database: mysql   # 추가 해준 부분
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: false
#        default_batch_fetch_size: 1000

jwt:
  expire-length : 3600000
  secret: "가나다라마바사아자차카타파하"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.example.simple.config: debug

## AWS Account Credentials (AWS 접근 키)
#  cloud.aws.credentials.accessKey={액세스키}
#  cloud.aws.credentials.secretKey={액세스 시크릿 키}
#
#  # AWS S3 bucket Info (S3 버킷정보)
#  cloud.aws.s3.bucket={S3 버킷 이름)
#  cloud.aws.region.static=ap-northeast-2 (S3 버킷 지역)
#  cloud.aws.stack.auto=false
#
#  # file upload max size (파일 업로드 크기 설정)
#  spring.servlet.multipart.max-file-size=20MB
#  spring.servlet.multipart.max-request-size=20MB

cloud:
  aws:
    credentials:
      access-key: AKIATVRAJUBD5MTOV6CU
      secret-key: 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
    s3:
      region: ap-northeast-2
      bucket: sparcs-2023-startup-hackathon-m-1
    stack:
      auto: false


