spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: false

jwt:
  expire-length : 3600000
  secret: "가나다라마바사아자차카타파하"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.example.simple.config: debug